#!/usr/bin/env bash

args=(
  --destination _serve
  --future
  --drafts
  --incremental
  --livereload
  --host 0.0.0.0
)

if [ "${DISPLAY:-}" != "" ] && [ "$(uname)" = "Linux" ]; then
  args+=(--open-url)
fi

exec bundle exec jekyll serve "${args[@]}"
